### ISSUE TITLE
Ability to customise search URL for suggestions

### ISSUE THREAD

**Issue by schrodincat** [deanishe/alfred-searchio#19]
Some web services return suggestions with links to corresponding web pages, in addition to suggested search terms, effectively providing actual search results in the GET response.

It would be reasonable to use those links instead of `_search_url` URL, when picking items in the list, so the user can skip search page and go straight to the actual result, but as far as I understand, it's not possible without altering of inner workings of the workflow.

Please, consider to add this functionality. Here is [JSON response](https://github.com/deanishe/alfred-searchio/files/1408955/kinopoisk.ru_suggestions_response.txt) format for the reference, which is used by kinopoisk.ru.

**Comment by deanishe** [comment]
As the current version of the workflow is based on subclassing, it's possible to override any behaviour you want to change. What you're asking for is already possible.

This will change in v2, however, where all searches will be defined in configuration files, not code.

**Comment by schrodincat** [comment]
Thank you for clarification, I'll change implementation of support for kinopoisk.ru to customise search URL for suggestions and open another pull request when it's ready.

Please, consider to leave the possibility customise search URL for suggestions in v2.

**Comment by deanishe** [comment]
> Please, consider to leave the possibility customise search URL for suggestions in v2.

I will. Using configuration files opens up the possibility of re-implementing (critical parts of) the workflow in a compiled language, at the cost of preventing deeper customisation like you're requesting.

The thing is, this is the first time anyone has requested anything like this. It seems that autosuggest APIs that link directly to the search results are rare things…

**Comment by schrodincat** [comment]
> It seems that autosuggest APIs that link directly to the search results are rare things…

Actually, no, it's not the case. Off the top of my head: kinopoisk.ru, imdb.com, twitch.tv, plex.tv, store.playstation.com... I'm sure, there are tons of others.

**Comment by deanishe** [comment]
> I'm sure, there are tons of others

There doubtless are, but you're the first person to raise an issue about one, which is the relevant metric for the workflow…

> imdb.com

That's an interesting one. I'm sure that IMBd is a very popular search (and one I'd like to support), but is has a very unusual API, which is essentially out of the question for a configuration-file-based workflow (that doesn't special-case IMBd).

I've been holding back releasing a second version, as I've not had a clear idea about how best to implement it such that it supports as many search engines as possible while remaining relatively fast.

You've convinced me that I should use a hybrid model whereby engines can be defined either by configuration files or by code.

If I do re-implement parts in Go or the like for speed, then folks who want an engine with different behaviour will just have to submit a PR rather than drop their own Python modules in a directory.

**Comment by schrodincat** [comment]
> If I do re-implement parts in Go or the like for speed, then folks who want an engine with different behaviour will just have to submit a PR rather than drop their own Python modules in a directory.

That would be only mild inconvenience and more than justified tradeoff for faster performance. It's  even better in some sense because new engines are end up here and will be accessible for all users after PR.
