### ISSUE TITLE
Add ability to retrieve query text with a modifier keypress  

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#36]
Currently if you cmd + c on a query result you get a link for the search. This is great. I do however want to ditch [Anycomplete](https://github.com/nathancahill/Anycomplete) and use Searchio for its purpose of filling out text from a query and pasting it to the screen as well as making searches. 

For that I need to retrieve the actual item text and put it into clipboard so I can then paste the text with CMD + V or do something else with it.

Will this be possible to add ability to get the Item's text with a modifier keypress or it goes against the way Searchio is built? 

For my case I only need to use this from DuckDuckGo's script filter.

**Comment by deanishe** [comment]
It's simple enough to change what's copied to the suggestion text instead of the URL.

But I'm not going to do that just because a single user wants to do something weird with the workflow that is *way* outside of what it's designed to do.

Please stop submitting issues asking me to alter my workflows to suit the unusual things you do with your computer. If you don't have a reason why a feature would be useful to lots of "normal" users, please don't submit a request for it.

I'll leave the issue open to see if anyone else has a more broadly-applicable reason for the change.

**Comment by nikitavoloboev** [comment]
> Please stop submitting issues asking me to alter my workflows to suit the unusual things you do with your computer.

Sure. Won't ask again.
