### ISSUE TITLE
File Not Found Error 

### ISSUE THREAD

**Issue by swojit** [deanishe/alfred-searchio#50]
![image](https://user-images.githubusercontent.com/12771661/46753526-f8f6da00-cc74-11e8-8f12-8f730f947aa4.png)
I am getting the above issue when I try any of the searches. What could be the issue? I am on MacOS Mojave and the latest version of searchio

**Comment by swojit** [comment]
Hmm, it got fixed when I installed the google and amazon searches again on the searchio config. Closing this.

**Comment by deanishe** [comment]
Yeah, if you get an error like this, run `searchio reload` to re-create your searches. This is done automatically after you add or delete a search, which is why the problem was fixed.

Also, if you run into issues in future (with any workflow), don't post a screenshot. Post the output in Alfred's debugger.
