### ISSUE TITLE
Google Maps not returning search results

### ISSUE THREAD

**Issue by Baggydawg** [deanishe/alfred-searchio#58]
Hi,

Everything else is working but for some reason just maps isn't returning any results.

The most recent post I could find was 4 years ago, and maybe something has changed since then? Either way I'm not sure how to fix it. I've already removed and reinstalled the maps search engine.

**Comment by deanishe** [comment]
> Everything else is working but for some reason just maps isn't returning any results.

The workflow works fine. The problem is most likely with your API key for Google Places (which you have set, right?) If it previously worked for you, you probably need to enable billing.

You don't get an error in the workflow for a bad API key because the Google server still responds with `200 OK`, instead of a code that indicates an error.

Try this command in your shell to see the server response:

```
curl -L 'https://maps.googleapis.com/maps/api/place/autocomplete/json?input=trafalgar%20square&language=en&key=YOUR_GOOGLE_PLACES_API_KEY'
```
